### ISSUE TITLE
st3 can't browse packages after fixing the input method bug

### ISSUE THREAD

**Issue by idealvin** [whitequark/sublime-imethod-fix#1]
Yeah, It works well, but st3 can't browse the packages from preference any more after fixing input method bug.

**Comment by whitequark** [comment]
What exactly are you doing and what do you mean by "can't"?

**Comment by idealvin** [comment]
Activate the input method in sublime text 3 first, then click "Preference" ---> "Browse Packages",
It doesn't work!  I'm working on ubuntu 14.04

**Comment by whitequark** [comment]
Hm, works for me on Debian testing.

Are there any messages when you run ST3 from the terminal?

**Comment by idealvin** [comment]
nothing from the terminal, the input method work well,  
It just ends timeout with the package dir unopened.  
St3 can open package dir normally without fixing im.

**Comment by idealvin** [comment]
It seems compiz not work well  
When click the "browse pack", the mouse pointer spins for some time and then timeout, failed to open the package dir

**Comment by whitequark** [comment]
Try opening the Python console and entering `import os` `os.putenv("LD_PRELOAD", "")`, then browsing packages.

**Comment by idealvin** [comment]
when I cd to /opt/sublime_text and run  ./sublime_text, there is no problem.  
when run with /opt/sublime_text/sublime_text, the problem appears again

**Comment by whitequark** [comment]
Did the `os.putenv` trick do something?

**Comment by idealvin** [comment]
no, it doesn't help

**Comment by whitequark** [comment]
Hm, no idea.

**Comment by idealvin** [comment]
Finally I solved it by fixing the /opt/sublime_text/sublime_text like this:

``` cpp
cd /opt/sublime_text
export GTK_IM_MODULE=xim
export LD_PRELOAD=./libsublime_text-xim-xcompose.so
exec ./sublime_text.orig "$@"
```
