### ISSUE TITLE
Does it fix this bug?

### ISSUE THREAD

**Issue by BarbzYHOOL** [whitequark/sublime-imethod-fix#3]
I have a bug where I can't type "êôûöü" instead it divides in two like this "^e^o^u¨o¨u".

Does this patch fix it?

**Comment by whitequark** [comment]
I don't think so, sorry. This seems like your input method enters decomposed characters and in the wrong order. I am unfortunately not able to assist you with this.

**Comment by BarbzYHOOL** [comment]
ok ty
